#! /data/data/com.termux/files/usr/bin/bash

# Date:         May 29 2022 at 10:43:19 AM
# Description:  Get content from the web

set -e

if [[ $# -eq 0 ]]; then
    echo -e "Usage: $0 <video-url>"
    exit 0
else
    url=$1
fi

if [ $(uname -o | grep -io "Android") ]; then
    aoutput=$HOME/storage/music
    voutput=$HOME/storage/movies
    mkdir -p $aoutput
    mkdir -p $voutput
else
    aoutput=$HOME/Music
    voutput=$HOME/Videos
fi

echo -e "Options"
echo -e "\t1) TouTube Audio"
echo -e "\t2) TouTube Audio playlist"
echo -e "\t3) TouTube Video"
echo -e "\t4) TouTube Video playlist"
echo -e "\t5) TikTok Video"
echo -e "\nOutput\n\tAudio: $aoutput\n\tVideo: $voutput"

echo -ne "\nChoice: "
read CHOICE
case $CHOICE in
    1)
        youtube-dl --audio-format mp3 --extract-audio --no-playlist $url -o "$aoutput/%(title)s %(id)s.%(ext)s" # --quiet
        ;;
    2)
        youtube-dl --audio-format mp3 --extract-audio --yes-playlist $url -o "$aoutput/%(title)s %(id)s.%(ext)s" # --quiet
        ;;
    3)
        youtube-dl --no-playlist --format mp4 $url -o "$voutput/%(title)s %(id)s.%(ext)s" # --quiet
        ;;
    4)
        youtube-dl --yes-playlist --format mp4 $url -o "$voutput/%(title)s %(id)s.%(ext)s" # --quiet
        ;;
    5)
        mkdir -p "$voutput/tiktok"
        tiktok-dl $url "$voutput/tiktok"
        ;;
esac

echo -e "\n[!] Done!"
